# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'QTGifSearcher' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for QTGifSearcher

pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.8'
pod 'FLAnimatedImage', '~> 1.0'


  target 'QTGifSearcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
